# Generated by Django 5.0 on 2023-12-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_userinformation_user_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='model_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
