# Generated by Django 5.0 on 2023-12-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_usermodel_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='scores',
        ),
    ]
