# Generated by Django 5.0 on 2023-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_usermodel_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='clustering_algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('em', 'Expectation Maximization')], default='kmeans', max_length=10),
        ),
    ]
