# Generated by Django 5.0 on 2023-12-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_usermodel_clustering_algorithm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='kmeans_centers',
            new_name='centers',
        ),
    ]
